// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/chat.proto

package com.talent.aio.examples.im.common.packets;

public interface JoinRespBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.talent.aio.examples.im.common.packets.JoinRespBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 time = 1;</code>
   */
  long getTime();

  /**
   * <code>.com.talent.aio.examples.im.common.packets.JoinGroupResult result = 2;</code>
   */
  boolean hasResult();
  /**
   * <code>.com.talent.aio.examples.im.common.packets.JoinGroupResult result = 2;</code>
   */
  com.talent.aio.examples.im.common.packets.JoinGroupResult getResult();
  /**
   * <code>.com.talent.aio.examples.im.common.packets.JoinGroupResult result = 2;</code>
   */
  com.talent.aio.examples.im.common.packets.JoinGroupResultOrBuilder getResultOrBuilder();

  /**
   * <code>string group = 32;</code>
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 32;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();
}
